name: 'Deploy to Dokku'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Gunakan versi terbaru agar lebih stabil

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 178.248.73.107 >> ~/.ssh/known_hosts


      - name: Push to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'dokku@178.248.73.107:django'  # Perbaiki format remote URL
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: "main"  # Pastikan branch yang dipush adalah main