name: Auto Push to Dokku and GitHub

on:
  push:
    branches:
      - main  # Jalan saat ada push ke "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode dari GitHub
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 178.248.73.107 >> ~/.ssh/known_hosts

      - name: Push ke Dokku
        run: git push ssh://dev@178.248.73.107/django main